### ISSUE TITLE
Function with string <style> makes the build fail

### ISSUE THREAD

**Issue by zamkevich** [kaisermann/svelte-preprocess#101]
**This function in Script block makes the build fail**
```
  export let style = (obj) => { 
    return `<style>${obj}</style>`
  };
```
**this is not**
```
  export let style = (obj) => { 
    let tag = 'style';
    return `<${tag}>${obj}</${tag}>`
  }; 
```
**Error**
```
> Building...
> /src/routes/index.svelte:1:3: Unknown word
CssSyntaxError: /src/routes/index.svelte:1:3: Unknown word
    at Input.error (/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/node_modules/postcss/lib/parser.js:563:22)
    at Parser.other (/node_modules/postcss/lib/parser.js:168:12)
    at Parser.parse (/node_modules/postcss/lib/parser.js:77:16)
    at parse (/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/node_modules/postcss/lib/processor.js:117:23)
    at process (/node_modules/svelte-preprocess/dist/transformers/postcss.js:1:512)
    at Object.transformer [as postcss] (/node_modules/svelte-preprocess/dist/transformers/postcss.js:1:1200)
```

**To Reproduce**
Use default Sapper build with Rollapp config:
```
…
import sveltePreprocess from 'svelte-preprocess';
const preprocess = sveltePreprocess({
	postcss: true
});

…

client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				dev,
				hydratable: true,
				preprocess,
			}),
…

server: {
		input: config.server.input(),
		output: config.server.output(),
		plugins: [
			replace({
				'process.browser': false,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess,
				generate: 'ssr',
				dev
			}),
…
```
and empty postcss.config.js
```
module.exports = {
  parser: "sugarss",
  map: true,
};
```
add <Script> block to /src/routes/index.svelte with error function 
```
<script>
  export let style = (obj) => { 
    return `<style>${obj}</style>`
  };
</script>
```
make build > npm run build

**Comment by kaisermann** [comment]
Hey 👋 that's an actual limitation of the way svelte captures your script/style content to pass them to preprocessors. It uses a RegExp meaning basically "gimme everything between <style><style/>", independent of context.

**Comment by zamkevich** [comment]
I understand, but why not add exceptions for ${…} and var
```
`<style> ${ … } <style>       // exception for any ${ … }
 
"<style>" + var + "<style>"   // exception for for any + var + but not for + "string" +
'<style>' + var + '<style>'   // exception for for any + var + but not for + 'string' +
```

**Comment by kaisermann** [comment]
That is something only Svelte can do. Preprocessors (like `svelte-preprocess`) just receive the matched content of the `style` and `script` tags.

**Comment by zamkevich** [comment]
Yeah, I know a way with ```document.createElement('style')``` but i make it by my way:

```
<script>
  let style = (obj) => { 
    let tag = 'style';
    return `<${tag}>${obj}</${tag}>`
  }; 
<script>

<!-- dynamic styles from DB -->
{@html style(styles.head_img)}

<!-- static styles -->
<styel>
…
</style>
```

**Comment by m59peacemaker** [comment]
This works, too:
```html
{@html
  `
    <${'style'}>
      body {
        /* etc */
      }
    </${'style'}>
  `
}
```
