### ISSUE TITLE
Auto-compile imported scss files in style tags when they have changed

### ISSUE THREAD

**Issue by vexkiddy** [kaisermann/svelte-preprocess#111]
Consider this code example

```
<style lang='scss'>
   @import '/src/css/variables.scss';

   $border-dark: rgba($base-color, 0.88);

   .alert {
     border: 1px solid $border-dark;
   }
</style>
```

Currently when I make changes to the ```variables.scss``` no components that import it update or reflect its changes. I have to save each component that imports it. Is there a way to get this working currently or is this a feature that needs building? Basically to recompile all affected files when imported .scss files are changed?

I'm currently using **Svelte 3** and **Parcel** for my build along with a ```svelte.config.js``` file the contents of which look like this:

```
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
  preprocess: sveltePreprocess()
};

```

**Comment by kaisermann** [comment]
Hey @vexkiddy 👋 Would you be able to provide a minimal repro? This was supposed to be working, at least for rollup and webpack.

**Comment by vexkiddy** [comment]
Hiya @kaisermann 👍 I quickly put something together for you here: https://github.com/vexkiddy/parcel-svelte-sass

When you have it running and change the linked **variables.scss** you'll see that nothing updates. You have to go into the component and save it, then it updates. Thanks for taking a look!

**Comment by kaisermann** [comment]
Ah! This is happening because `parcel-plugin-svelte` doesn't handle the returned `dependencies` array from the `svelte.preprocess()` method. I tried searching on how to add these files to parcel's  watch list but couldn't find anything.

Examples: [`rollup-plugin-svelte/index.js#L234`](https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L234) and [`svelte-loader/index.js#L143`](https://github.com/sveltejs/svelte-loader/blob/master/index.js#L143)

**Comment by kaisermann** [comment]
Should be working in `parcel-plugin-svelte >= v4.0.6` 🎉

**Comment by vexkiddy** [comment]
Amazing! Will check tomorrow morning! Many thanks!

**Comment by vexkiddy** [comment]
Hmm.. seem to be getting a 'HyphenMinus is expected' now that i've updated all the NPM packages.. will have to look into this properly tomorrow! Will get back to you if I get it all working correctly! :D

**Comment by vexkiddy** [comment]
Ok.. it works in the test repro I made for you, so the error I'm getting must be from another package I'm using in my main project! So all good! Amazing work! Thank you so much! 👍 💯

**Comment by rhernandog** [comment]
Hey sorry to re-open this but I'm facing the same issue running on the webpack template. I'm attaching a simple example. I ran `npm run dev` and then, if I make a change in the imported `scss` file the live view doesn't reload and I have to make a change in the `svelte` file so the changes are reflfected.

[svelte-sass-reload.zip](https://github.com/kaisermann/svelte-preprocess/files/4181094/svelte-sass-reload.zip)

**Comment by kaisermann** [comment]
Hey @rhernandog! Sorry but I was unable to reproduce your issue. I just tried `npm run dev` in your example, modified the `background-color: green` and the browser was promptly updated.

**Comment by rhernandog** [comment]
@kaisermann Thanks!!!
Mhhh.... perhaps the OS could be the issue?
I created a new folder downloaded the ZIP file, ran `npm install` and then `npm run dev`, updated something in `app.scss` and nothing happened.

I'm working on Win10 Pro 64, running the CLI on windows powershell.

I even made a small screen capture:

![svelte-reload-sass](https://user-images.githubusercontent.com/4622323/74258934-d98f1780-4cd5-11ea-9496-fb343a065166.gif)

**Comment by kaisermann** [comment]
Oh boy, yeah... probably an OS issue. 

Which reminds me of an issue I had with some scss related tests regarding the returned dependency list. I don't have a windows machine to use right now, but would you be able to log the result of this line: https://github.com/kaisermann/svelte-preprocess/blob/master/src/transformers/scss.ts#L43 (only the `result.stats.includedFiles`)?

**Comment by rhernandog** [comment]
> but would you be able to log the result of this line
I'm a bit off my element Christian. I cloned the repo, installed all the dependencies, added a console call in the file and run the test suite. This is what I got (is a lot though)

```
PS C:\Users\rhern\Desktop\svelte-preprocess-master> npm run test

> svelte-preprocess@3.4.0 test C:\Users\rhern\Desktop\svelte-preprocess-master
> jest

 PASS  test/autoProcess/script.test.ts (29.622s)
 PASS  test/transformers/postcss.test.ts (8.157s)
  ● Console

    console.error src/transformers/postcss.ts:1195
      Error: No PostCSS Config found in: C:\Users\rhern\Desktop\svelte-preprocess-master
          at C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\postcss-load-config\src\index.js:91:15
          at Object.transformer [as postcss] (C:\Users\rhern\Desktop\svelte-preprocess-master\src\transformers\postcss.ts:1184:15)
          at style (C:\Users\rhern\Desktop\svelte-preprocess-master\src\autoProcess.ts:2243:36)
          at C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:122:34
          at async Promise.all (index 0)
          at replace_async (C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:60:48)
          at Object.preprocess (C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:115:12)
          at Object.<anonymous> (C:\Users\rhern\Desktop\svelte-preprocess-master\test\transformers\postcss.test.ts:25:26)
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []

 PASS  test/autoProcess/autoProcess.test.ts
  ● Console

    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.warn src/autoProcess.ts:2131
      [svelte-preprocess] For svelte >= v3, instead of onBefore(), prefer to prepend a preprocess object to your array of preprocessors

 PASS  test/autoProcess/markup.test.ts
 FAIL  test/processors.test.ts (42.409s)
  ● Console

    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.error src/transformers/postcss.ts:1195
      Error: No PostCSS Config found in: C:\Users\rhern\Desktop\svelte-preprocess-master
          at C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\postcss-load-config\src\index.js:91:15
          at transformer (C:\Users\rhern\Desktop\svelte-preprocess-master\src\transformers\postcss.ts:1184:15)
          at style (C:\Users\rhern\Desktop\svelte-preprocess-master\src\processors\postcss.ts:640:34)
          at C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:122:34
          at async Promise.all (index 0)
          at replace_async (C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:60:48)
          at Object.preprocess (C:\Users\rhern\Desktop\svelte-preprocess-master\node_modules\svelte\src\compiler\preprocess\index.ts:115:12)
          at Object.<anonymous> (C:\Users\rhern\Desktop\svelte-preprocess-master\test\processors.test.ts:40:28)

  ● processor - sass › should support external src files

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invok
ed within the 5000ms timeout specified by jest.setTimeout.Error:

      36 | STYLE_LANGS.forEach(([lang, ext, processor, options]) => {
      37 |   describe(`processor - ${lang}`, () => {
    > 38 |     it('should support external src files', async () => {
         |     ^
      39 |       const template = `<style src="./fixtures/style.${ext}"></style><div></div>`;
      40 |       const preprocessed = await preprocess(template, [processor(options)]);
      41 |       expect(preprocessed.toString()).toMatch(CSS_PATTERN);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/processors.test.ts:38:5)
      at test/processors.test.ts:37:3
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/processors.test.ts:36:13)

 PASS  test/transformers/globalStyle.test.ts
 PASS  test/autoProcess/style.test.ts
  ● Console

    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []

 PASS  test/transformers/pug.test.ts
 PASS  test/transformers/stylus.test.ts
 PASS  test/transformers/scss.test.ts
  ● Console

    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      []
    console.log src/transformers/scss.ts:588
      -------
      logging promise result
    console.log src/transformers/scss.ts:592
      [
        "C:/Users/rhern/Desktop/svelte-preprocess-master/test/fixtures/style.scss"
      ]

 PASS  test/utils.test.ts
 PASS  test/autoProcess/externalFiles.test.ts
 PASS  test/transformers/less.test.ts
 PASS  test/transformers/typescript.test.ts (49.468s)
  ● Console

    console.log src/transformers/typescript.ts:3167
      test/App.svelte:1:5 - error TS2322: Type '10' is not assignable to type 'string'.

      1 let label:string = 10
            ~~~~~

    console.log src/transformers/typescript.ts:3167
      test/App.svelte:1:20 - error TS2307: Cannot find module './fixtures/NonExistent.svelte'.

      1 import Nested from './fixtures/NonExistent.svelte'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    console.log src/transformers/typescript.ts:3167
      test/App.svelte:1:20 - error TS2307: Cannot find module './relative/yaddaYadda.js'.

      1 import Nested from './relative/yaddaYadda.js'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

    console.log src/transformers/typescript.ts:3167
      test/App.svelte:1:20 - error TS2307: Cannot find module './relative/noExtension'.

      1 import Nested from './relative/noExtension'
                           ~~~~~~~~~~~~~~~~~~~~~~~~


------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------------|---------|----------|---------|---------|-------------------
All files         |   96.14 |    91.53 |   96.91 |   97.71 |
 src              |   99.35 |    98.59 |     100 |     100 |
  autoProcess.ts  |   98.46 |    97.56 |     100 |     100 | 99
  index.ts        |     100 |      100 |     100 |     100 |
  utils.ts        |     100 |      100 |     100 |     100 |
 src/processors   |   84.38 |       50 |    87.5 |   92.16 |
  coffeescript.ts |   88.89 |       50 |     100 |     100 | 15
  globalStyle.ts* |   16.67 |        0 |       0 |      20 | 4,6,9,11
  less.ts         |   88.89 |       50 |     100 |     100 | 12
  postcss.ts      |     100 |      100 |     100 |     100 |
  pug.ts          |     100 |      100 |     100 |     100 |
  scss.ts         |   90.91 |       75 |     100 |     100 | 12
  stylus.ts       |   88.89 |       50 |     100 |     100 | 11
  typescript.ts   |   88.89 |       50 |     100 |     100 | 11
 src/transformers |   98.82 |    92.39 |     100 |   98.77 |
  coffeescript.ts |     100 |      100 |     100 |     100 |
  globalStyle.ts  |     100 |      100 |     100 |     100 |
  less.ts         |     100 |      100 |     100 |     100 |
  postcss.ts      |     100 |      100 |     100 |     100 |
  pug.ts          |     100 |    83.33 |     100 |     100 | 66
  scss.ts         |   93.75 |    90.91 |     100 |   93.33 | 33
  stylus.ts       |     100 |      100 |     100 |     100 |
  typescript.ts   |    98.8 |    90.91 |     100 |    98.7 | 127
 src/typings*     |       0 |      100 |     100 |       0 |
  index.ts*       |       0 |      100 |     100 |       0 | 3,5
  modules.d.ts    |       0 |        0 |       0 |       0 |
------------------|---------|----------|---------|---------|-------------------

Test Suites: 1 failed, 13 passed, 14 total
Tests:       1 failed, 88 passed, 89 total
Snapshots:   0 total
Time:        58.096s, estimated 64s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-preprocess@3.4.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-preprocess@3.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rhern\AppData\Roaming\npm-cache\_logs\2020-02-11T21_02_41_932Z-debug.log
```
In the list I added an asterisk after the elements that came out in red.

I don't know if this is the right way to do what you need, but let me know if there is anything else.

Best,
Rodrigo.

**Comment by kaisermann** [comment]
Thanks! It was kind of that 😁 I meant adding a `console.log` to the installed package `./node_modules/svelte-preprocess/...` to see the paths being returned. If I'm not mistaken, `node-sass` returns them as unix paths, not window ones. Maybe this has something to do with your case 🤔

**Comment by rhernandog** [comment]
Ahh... sorry, I was a bit lost in the production file since it's minified.

This is the log of `result.stats` after running `npm run dev`:

```
{
  "entry": "data",
  "start": 1581515108039,
  "includedFiles": [
    "D:/Web Apps/Svelte/webpack-sass-startup/template-webpack/src/app.scss"
  ],
  "end": 1581515108086,
  "duration": 47
}
```

After making a change in the `scss` file nothing happens in the CLI though.

Finally I've used node sass with Vue and React bundles using webpack dev server without any issues when the files are updated.
