### ISSUE TITLE
unexpected token "indent"

### ISSUE THREAD

**Issue by tobias-kuendig** [kaisermann/svelte-preprocess#32]
I'm playing around with your great plugin and the sveltejs/template project. I'm having an error using pug, maybe I'm doing something wrong.

I have the following component:

```html
<template lang="pug">
	h1 Hello
</template>

<script>
	export let name;
</script>

<style lang="stylus">
	h1
		color red
</style>
```

The following error is returned:

```
[!] (svelte plugin) Error: [svelte-preprocess] Error transforming 'pug'. Message:
/svelte-test/src/App.svelte:2:1
    1| 
  > 2|  h1 Hello
-------^
    3| 
    4| 
    5| <script>

unexpected token "indent"
src/App.svelte
Error: [svelte-preprocess] Error transforming 'pug'. Message:
/svelte-test/src/App.svelte:2:1
    1| 
  > 2|  h1 Hello
-------^
    3| 
    4| 
    5| <script>

unexpected token "indent"
    at throwError (/svelte-test/node_modules/svelte-preprocess/src/utils.js:14:9)
    at exports.runTransformer (/svelte-test/node_modules/svelte-preprocess/src/utils.js:77:5)
    at /svelte-test/node_modules/svelte-preprocess/src/autoProcess.js:77:38
    at Object.markup (/svelte-test/node_modules/svelte-preprocess/src/autoProcess.js:135:14)
    at preprocessOptions.(anonymous function).args (/svelte-test/node_modules/rollup-plugin-svelte/index.js:214:53)
    at /svelte-test/node_modules/svelte/compiler.js:23838:38
    at Generator.next (<anonymous>)
    at /svelte-test/node_modules/svelte/compiler.js:23791:72
    at new Promise (<anonymous>)
    at __awaiter (/svelte-test/node_modules/svelte/compiler.js:23787:13)

```

For reference, the rollup config:

```js
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import autoPreprocess from 'svelte-preprocess';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			},

			preprocess: autoPreprocess()
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/rollup-plugin-commonjs
		resolve(),
		commonjs(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false,
		chokidar: false
	}
};
```

**Comment by kaisermann** [comment]
Oooops, that was a bug 😉 Fixed on `v2.9.1` 🎉
