### ISSUE TITLE
<style lang="scss"> does not seem to work

### ISSUE THREAD

**Issue by mtrifilo** [kaisermann/svelte-preprocess#48]
I've been following the examples and recommendations from the documentation, but after hours of debugging, I'm getting the same error: 
```bash
rollup v1.16.3
bundles src/browserEntry.js → public/bundle.js...
LiveReload enabled
public/design.css 1722 B
created public/bundle.js in 971ms
bundles src/App.svelte → public/App.js...
[!] (plugin svelte) ParseError: Selector is expected
src/components/NavLink.svelte
17: 
18: <style lang="scss">
19:   $color: red;
      ^
20:   div {
21:     color: $color;
ParseError: Selector is expected
    at error$1 (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$2.error (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/parse/index.ts:93:3)
    at Object.read_style [as read] (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/parse/read/style.ts:20:11)
    at tag (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/parse/state/tag.ts:221:27)
    at new Parser$2 (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/parse/index.ts:45:12)
    at parse$2 (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/parse/index.ts:208:17)
    at parse (/home/matt/Matt/matttrifilo.com-svelte/node_modules/svelte/src/compiler/compile/index.ts:68:14)
    at preprocessPromise.then.code (/home/matt/Matt/matttrifilo.com-svelte/node_modules/rollup-plugin-svelte/index.js:252:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

```

Component:
```
<script>
    import { Link } from 'svelte-routing';

    export let to = '';

    function getProps({ location, href, isPartiallyCurrent, isCurrent }) {
        const isActive = href === '/'
            ? isCurrent
            : isPartiallyCurrent || isCurrent;

            if (isActive) {
                return { class: 'active' };
            }
            return {};
    }
</script>

<style lang="scss">
  $color: red;
  div {
    color: $color;
  }
</style>

<Link to="{to}" getProps="{getProps}">
    <div>test</div>
    
    <slot />
</Link>
```

rollup.config.js:
```js
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import { scss, postcss } from 'svelte-preprocess';
import scssPlugin from 'rollup-plugin-scss';

const isDev = Boolean(process.env.ROLLUP_WATCH);

export default [
  // Browser bundle
  {
    input: 'src/browserEntry.js',
    output: {
      sourcemap: true,
      format: 'iife',
      name: 'app',
      file: 'public/bundle.js',
    },
    plugins: [
      scssPlugin({
        output: 'public/design.css',
      }),
      svelte({
        hydratable: true,
        css: css => {
          css.write('public/bundle.css');
        },
        preprocess: [
          scss(),
          postcss({
            plugins: [
              require('autoprefixer')({
                browsers: 'last 2 versions',
              }),
            ],
          }),
        ],
      }),
      resolve(),
      commonjs(),
      isDev &&
        livereload({
          watch: 'public',
        }),
      !isDev && terser(),
    ],
  },
  // Server bundle
  {
    input: 'src/App.svelte',
    output: {
      sourcemap: false,
      format: 'cjs',
      name: 'app',
      file: 'public/App.js',
    },
    plugins: [
      svelte({
        generate: 'ssr',
      }),
      resolve(),
      commonjs(),
      !isDev && terser(),
    ],
  },
];
```

Is there something I'm missing?

**Comment by watzon** [comment]
Having the exact same issue

**Comment by kaisermann** [comment]
Hello! You have to also define the `preprocess` property on the server build: https://github.com/kaisermann/svelte-preprocess#with-sapper

**Comment by watzon** [comment]
That seems to have fixed the errors in the console @kaisermann :) now if I could just get VS Code to stop marking it as an error

**Comment by kaisermann** [comment]
@watzon do you have a `svelte.config.js` file (https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-386035232)? If not, I'd recommend creating one and importing it in your `rollup.config.js` 🤙

**Comment by watzon** [comment]
@kaisermann I created one, but I have no idea how to make that work with `svelte-preprocess`. The example configs in that issue just use `node-sass`

**Comment by kaisermann** [comment]
@watzon It accepts the same options as `rollup-plugin-svelte`. You just need to setup the `preprocess` property in the same way you set it in `rollup.config.js`. I have an old example [here](https://github.com/stone-payments/pos-mamba-sdk/blob/develop/packages/configs/svelte/index.js)

**Comment by mtrifilo** [comment]
Thank you @kaisermann, adding the `preprocess` config to the server build config was exactly what I was missing :tada:. I really appreciate the quick response. 

I'll close this issue, though I'm interested in the VS Code linting discussion as well. I'll try out the solution you linked for creating a `svelte.config.js` file.
